---
title: "blogdown"
author: "Brad Bailey"
date: "2/26/2020"
output: ioslides_presentation
---

## Hugo

Static website generator:  

- A static website is "a web page that is delivered to the user's web browser exactly as stored" ([Wikipedia](https://en.wikipedia.org/wiki/Static_web_page))
- Installed automatically when you install blogdown
- Great software, except missing support for Rmarkdown files  

Blogdown builds on Hugo's speed and reliability to enable creation of websites with Rmarkdown support in RStudio!  

## blogdown

Functionality through the 'addins' dropdown menu, next to the 'panes' button:  

- Serve Site: Live, local preview of your website
- New Post
- Update Metadata: Conveniently edit the YAML of an existing post
- Insert Image

## blogdown cont.

Rmarkdown support allows for all the features we know and love, including:  

- Executeable R code chunks
- LaTeX math typesetting
- HTML Widgets and Shiny Apps
- Inline formatting e.g. subscripts and footnotes

However, you suffer some decrease in speed by using Rmarkdown compared to markdown.

## Reccomended workflow

1. Pick a [Theme](http://themes.gohugo.io)
2. Create a new project in Rstudio and call blogdown::new_site(theme = 'user/repo')
3. Edit the config.toml options
4. Edit the site: click the "Serve Site" Addin to view your website in Rstudio
5. Use the "New Post" Addin to create a new post, and create its content
6. Use the "Update Metadata" Addin to change the options for your post
7. Host your site!

## Deployment/Hosting

Once you've created your website locally, you need to host it on a server for the world to see.
There are a few options for free hosting services, but the authors reccomend [Netlify](https://www.netlify.com).

You can sign up for Netlify using your Github account! Once your account is created, you can either upload your 'public/' folder to launch your website immediately, or you can click "New site from Git" to select a Git repo that Netlify will use to create your site *continuously*! I reccommended you specify 'hugo' under 'Build Command' and 'public' for 'Publish Directory'.

That's it! You can now make changes to your website in RStudio, push to your repo, and Netlify will automatically update your site for you.

## Resources and references

- [The Book](https://bookdown.org/yihui/blogdown/)
- [Demo Website](https://blogdown-demo.rbind.io/)
- [Themes](http://themes.gohugo.io)
- [Netlify](https://www.netlify.com)

